# Min target
plugin 'cocoapods-binary'
platform :ios, '13.0'

## Pod install settings
## Configured for using separate projects (more performant)
install! 'cocoapods',
generate_multiple_pod_projects: true,
incremental_installation: true
use_modular_headers!
use_frameworks!

target 'CometChatPro-UIKit_Example' do
  pod 'CometChatPro-UIKit', :path => '../'
  pod 'CometChatPro', '2.1.1'
  pod 'IQKeyboardManager'
  pod 'Bagel', '~>  1.3.2', :configurations => ['Debug']
  target 'CometChatPro-UIKit_Example_Tests' do
    inherit! :search_paths
  end
end
