# Min target
plugin 'cocoapods-binary'
platform :ios, '13.0'

## Pod install settings
## Configured for using separate projects (more performant)
install! 'cocoapods',
generate_multiple_pod_projects: true,
incremental_installation: true
use_modular_headers!
use_frameworks!

# Open Source Cocoapods
source 'https://cdn.cocoapods.org'

target 'CometChatPro-UIKit_Example' do
# pod 'Firebase/Messaging'
  pod 'CometChatPro', '2.1.1', :binary => true
  pod 'IQKeyboardManager', :binary => true
  pod 'CometChatPro-UIKit', :path => '../'
  target 'CometChatPro-UIKit_Example_Tests' do
    inherit! :search_paths
    pod 'CometChatPro-UIKit', :path => '../'
  end
end
